require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarsController do

  # This should return the minimal set of attributes required to create a valid
  # Car. As you add validations to Car, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cars as @cars" do
      car = Car.create! valid_attributes
      get :index
      assigns(:cars).should eq([car])
    end
  end

  describe "GET show" do
    it "assigns the requested car as @car" do
      car = Car.create! valid_attributes
      get :show, :id => car.id.to_s
      assigns(:car).should eq(car)
    end
  end

  describe "GET new" do
    it "assigns a new car as @car" do
      get :new
      assigns(:car).should be_a_new(Car)
    end
  end

  describe "GET edit" do
    it "assigns the requested car as @car" do
      car = Car.create! valid_attributes
      get :edit, :id => car.id.to_s
      assigns(:car).should eq(car)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Car" do
        expect {
          post :create, :car => valid_attributes
        }.to change(Car, :count).by(1)
      end

      it "assigns a newly created car as @car" do
        post :create, :car => valid_attributes
        assigns(:car).should be_a(Car)
        assigns(:car).should be_persisted
      end

      it "redirects to the created car" do
        post :create, :car => valid_attributes
        response.should redirect_to(Car.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car as @car" do
        # Trigger the behavior that occurs when invalid params are submitted
        Car.any_instance.stub(:save).and_return(false)
        post :create, :car => {}
        assigns(:car).should be_a_new(Car)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Car.any_instance.stub(:save).and_return(false)
        post :create, :car => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car" do
        car = Car.create! valid_attributes
        # Assuming there are no other cars in the database, this
        # specifies that the Car created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Car.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => car.id, :car => {'these' => 'params'}
      end

      it "assigns the requested car as @car" do
        car = Car.create! valid_attributes
        put :update, :id => car.id, :car => valid_attributes
        assigns(:car).should eq(car)
      end

      it "redirects to the car" do
        car = Car.create! valid_attributes
        put :update, :id => car.id, :car => valid_attributes
        response.should redirect_to(car)
      end
    end

    describe "with invalid params" do
      it "assigns the car as @car" do
        car = Car.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Car.any_instance.stub(:save).and_return(false)
        put :update, :id => car.id.to_s, :car => {}
        assigns(:car).should eq(car)
      end

      it "re-renders the 'edit' template" do
        car = Car.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Car.any_instance.stub(:save).and_return(false)
        put :update, :id => car.id.to_s, :car => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car" do
      car = Car.create! valid_attributes
      expect {
        delete :destroy, :id => car.id.to_s
      }.to change(Car, :count).by(-1)
    end

    it "redirects to the cars list" do
      car = Car.create! valid_attributes
      delete :destroy, :id => car.id.to_s
      response.should redirect_to(cars_url)
    end
  end

end
