require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassengersController do

  # This should return the minimal set of attributes required to create a valid
  # Passenger. As you add validations to Passenger, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all passengers as @passengers" do
      passenger = Passenger.create! valid_attributes
      get :index
      assigns(:passengers).should eq([passenger])
    end
  end

  describe "GET show" do
    it "assigns the requested passenger as @passenger" do
      passenger = Passenger.create! valid_attributes
      get :show, :id => passenger.id.to_s
      assigns(:passenger).should eq(passenger)
    end
  end

  describe "GET new" do
    it "assigns a new passenger as @passenger" do
      get :new
      assigns(:passenger).should be_a_new(Passenger)
    end
  end

  describe "GET edit" do
    it "assigns the requested passenger as @passenger" do
      passenger = Passenger.create! valid_attributes
      get :edit, :id => passenger.id.to_s
      assigns(:passenger).should eq(passenger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Passenger" do
        expect {
          post :create, :passenger => valid_attributes
        }.to change(Passenger, :count).by(1)
      end

      it "assigns a newly created passenger as @passenger" do
        post :create, :passenger => valid_attributes
        assigns(:passenger).should be_a(Passenger)
        assigns(:passenger).should be_persisted
      end

      it "redirects to the created passenger" do
        post :create, :passenger => valid_attributes
        response.should redirect_to(Passenger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passenger as @passenger" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passenger.any_instance.stub(:save).and_return(false)
        post :create, :passenger => {}
        assigns(:passenger).should be_a_new(Passenger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Passenger.any_instance.stub(:save).and_return(false)
        post :create, :passenger => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passenger" do
        passenger = Passenger.create! valid_attributes
        # Assuming there are no other passengers in the database, this
        # specifies that the Passenger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Passenger.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => passenger.id, :passenger => {'these' => 'params'}
      end

      it "assigns the requested passenger as @passenger" do
        passenger = Passenger.create! valid_attributes
        put :update, :id => passenger.id, :passenger => valid_attributes
        assigns(:passenger).should eq(passenger)
      end

      it "redirects to the passenger" do
        passenger = Passenger.create! valid_attributes
        put :update, :id => passenger.id, :passenger => valid_attributes
        response.should redirect_to(passenger)
      end
    end

    describe "with invalid params" do
      it "assigns the passenger as @passenger" do
        passenger = Passenger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passenger.any_instance.stub(:save).and_return(false)
        put :update, :id => passenger.id.to_s, :passenger => {}
        assigns(:passenger).should eq(passenger)
      end

      it "re-renders the 'edit' template" do
        passenger = Passenger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Passenger.any_instance.stub(:save).and_return(false)
        put :update, :id => passenger.id.to_s, :passenger => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passenger" do
      passenger = Passenger.create! valid_attributes
      expect {
        delete :destroy, :id => passenger.id.to_s
      }.to change(Passenger, :count).by(-1)
    end

    it "redirects to the passengers list" do
      passenger = Passenger.create! valid_attributes
      delete :destroy, :id => passenger.id.to_s
      response.should redirect_to(passengers_url)
    end
  end

end
